
# Site settings
title: "William Beckett"
email: your-email@domain.com
description: >
  Nutanix and other things I come across
baseurl: ""
url: "https://williambeckett.me" 
words_per_minute: 180
repository: "wjbeckett/blog"

plugins:
  - jekyll-sitemap


# Site owner
owner:
  name: "William Beckett"
  email: "william@williambeckett.me"
  twitter_username: wjbeckett
  github_username:  wjbeckett

# Jekyll configuration
markdown: kramdown
permalink: /:year/:month/:title
exclude: [
  "node_modules",
  "LICENSE",
  "package.json",
  "README.md",
  "Gemfile",
  "gulpfile.babel.js",
  ".babelrc",
  ".gitignore",
  "sass",
  "scss",
  "validate",
  "bulma-docs.sass"
]

# Icons

fontawesome:   https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
iconic:        https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic.min.css
ionicons:      https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css
mdi:           https://cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css


# Variables

github:        https://github.com/wjbeckett
twitter:       https://twitter.com/wjbeckett
author:        "William"
