
# Site settings
title:         "William Beckett"
email: your-email@domain.com
description: >
  Nutanix and other things I come across
baseurl: ""
url: "https://wjbeckett.netlify.com" 
words_per_minute: 180
twitter_username: wjbeckett
github_username:  wjbeckett

# Build settings
markdown: kramdown
permalink: pretty
exclude: [
  "node_modules",
  "LICENSE",
  "package.json",
  "README.md",
  "Gemfile",
  "gulpfile.babel.js",
  ".babelrc",
  ".gitignore",
  "sass",
  "scss",
  "validate",
  "bulma-docs.sass"
]

# Icons

fontawesome:   https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
iconic:        https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic.min.css
ionicons:      https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css
mdi:           https://cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css

# Jekyll configuration


# Variables

github:        https://github.com/wjbeckett
twitter:       https://twitter.com/wjbeckett
author:        "William"
