# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:         "William Beckett"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Nutanix and other things I come across
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wjbeckett.netlify.com" # the base hostname & protocol for your site
twitter_username: wjbeckett
github_username:  wjbeckett

# Build settings
markdown: kramdown
permalink: pretty
exclude: [
  "node_modules",
  "LICENSE",
  "package.json",
  "README.md",
  "Gemfile",
  "gulpfile.babel.js",
  ".babelrc",
  ".gitignore",
  "sass",
  "scss",
  "validate",
  "bulma-docs.sass"
]

# Icons

fontawesome:   https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
iconic:        https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic.min.css
ionicons:      https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css
mdi:           https://cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css

# Variables

github:        https://github.com/wjbeckett
twitter:       https://twitter.com/wjbeckett
author:        "William"
